nginx:
  build: ./nginx
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    - "./nginx/logs:/var/log/nginx:rw"
    - "./nginx/sites-enabled:/etc/nginx/sites-enabled:rw"
  links:
    - "php70"
    - "php56"
  volumes_from:
    - htdocs
  restart: always

mysql56:
  build: ./mysql56
  container_name: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - "./mysql56/data:/var/lib/mysql:rw"
  volumes_from:
    - htdocs

php70:
  build: ./php70
  container_name: php7
  volumes:
    - "${HOME}/.ssh:/home/www/.ssh:ro"
    - "${SSH_AUTH_SOCK}:/tmp/agent.sock"
    - "./php70/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    - "./php70/conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
    - "./php70/conf/php.ini:/usr/local/etc/php/php.ini"
  volumes_from:
    - htdocs
  links:
    - mysql56
    - solr
    - mailhog
  ports:
    - "9001:9001"
  environment:
    TERM: xterm
    SSH_AUTH_SOCK: "/tmp/agent.sock"

php56:
  build: ./php56
  container_name: php5
  volumes:
    - "./php56/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    - "./php56/conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
    - "./php56/conf/php.ini:/usr/local/etc/php/php.ini"
  volumes_from:
    - htdocs
  links:
    - mysql56
    - solr
    - mailhog
  ports:
    - "9000:9000"
  environment:
    TERM: xterm
    
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  volumes_from:
    - htdocs
  ports:
    - "8080:80"
  links:
    - mysql56
  environment:
    PMA_HOST: mysql

htdocs:
  build: ./htdocs
  container_name: htdocs
  volumes:
    - "./htdocs/data:/var/www"
  tty: true

mailhog:
  container_name: mailhog
  image: mailhog/mailhog
  expose:
    - "1025"
    - "8025"
  ports:
    - "4900:8025"

solr:
  image: writl/solr-typo3
  container_name: solr
  ports:
    - "8282:8080"
  volumes_from: 
    - htdocs
  environment:
    TERM: xterm

# node:
#   build: ./node
#   container_name: node
#   volumes_from:
#     - htdocs
#   ports:
#     - "3000:3000"

# redis:
#   image: redis
#   container_name: redis
#   ports: 
#     - "6379:6379"
