nginx:
  build: ./nginx
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "./nginx/logs:/var/log/nginx:rw"
  links:
    - "php70"
    - "php56"
  volumes_from:
    - htdocs
  restart: always

mysql56:
  build: ./mysql56
  container_name: mysql56
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - "./mysql56/data:/var/lib/mysql:rw"
  volumes_from:
    - htdocs

php70:
  build: ./php70
  container_name: php7-fpm
  volumes_from:
    - htdocs
  links:
    - mysql56
  ports:
    - "9001:9001"
  environment:
    TERM: xterm

php56:
  build: ./php56
  container_name: php5-fpm
  volumes_from:
    - htdocs
  links:
    - mysql56
  ports:
    - "9000:9000"
  environment:
    TERM: xterm

htdocs:
  build: ./htdocs
  container_name: htdocs
  volumes:
    - "./htdocs:/var/www"
  tty: true
