nginx:
  build: ./nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "./nginx/logs:/var/log/nginx:rw"
  links:
    - "php70"
  volumes_from:
    - htdocs
  restart: always

mysql56:
  build: ./mysql56
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - "./mysql56/data:/var/lib/mysql:rw"
  volumes_from:
    - htdocs

php70:
  build: ./php70
  volumes_from:
    - htdocs
  links:
    - mysql56
  ports:
    - "9000:9000"
  environment:
    TERM: xterm

htdocs:
  build: ./htdocs
  volumes:
    - "./htdocs:/var/www"
  tty: true
