FROM nginx

MAINTAINER Andrii Valkiv "andrij2012@gmail.com"

# RUN  rm -rf /etc/nginx/conf.d/* \
#   && rm -rf /etc/nginx/sites-enabled/*

# COPY ./nginx.conf /etc/nginx/nginx.conf

VOLUME /home/andriy/www